---
- name: nginx 배포하기
  hosts: worker
  become: true

  tasks:
    - name: 배포할 Nginx 서비스 생성
      command: "whoami"
      command: "docker service create --name mynginx --replicas 3 --constraint 'node.role==worker' --with-registry-auth -p 8008:80 nginx"

