---
- name: 플레이북
  hosts: all
  become: true
  tasks:
    - name: Nginx installation
      yum:
        name: nginx
        state: present

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: start and enable nginx
      service:
        name: nginx
        state: started
        enabled: true

